services:
  - type: web
    name: backend
    runtime: python3
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: DB_NAME
        value: "render_db"
    healthCheckPath: "/api/"
    
  - type: web
    name: frontend
    runtime: node
    buildCommand: "cd frontend && yarn install && yarn build"
    startCommand: "cd frontend && serve -s build -l $PORT"
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
      - key: REACT_APP_BACKEND_URL
        value: "https://backend-latest.onrender.com"

databases:
  - name: postgres-db
    databaseName: render_db
    user: render_user
